### PR TITLE
Update our linting config

### PR DESCRIPTION
**Pull request by humitos**
Many updates to fit our linting preferences.

### CODE REVIEW

**Comment by ericholscher** [comment]
I'd much prefer to just use `black`, which has no configuration options, and will stop us from having to update these configs over time. In particular, it is starting to become a standard for python libs, similar to gofmt, but mainly I just really want to not have to configure our linters.

**Comment by humitos** [comment]
I never tried `black` but I saw that it's getting famous :)

I started using `yapf` because I had experience with it and I was able to match all the linting requirements that were needed.

@ericholscher `black` would be the replacement of what (`yapf`, `isort`, another or... all of them)?

**Comment by stsewd** [comment]
@humitos black what I like form black is that it starts and ends with the same AST, for that same reason it can't do the same as isort (https://github.com/ambv/black/issues/333), but I've seen that people use black together with https://github.com/asottile/reorder_python_imports.

What I don't like about black is that uses double quotes, what I like is that we don't have to write big config files.

What I don't like about black is the 88 columns by default (it's configurable), what I like about black is how it does the line breaks and wrapping, it's very smart.

What I don't like... No, that's all p: +1 on using black

**Comment by humitos** [comment]
OK. I will take some time in the following days to read about `black` and think if we should swap our current auto-linting to it.

I'm merging this PR since it doesn't interfers with the idea of using black or not.

**Pull request merged**
